import type { PackageBoundary } from "@runroot/config";

export {
  type ConfiguredAuditCatalogAssignmentChecklistStoreOptions,
  createConfiguredAuditCatalogAssignmentChecklistStore,
  createFileAuditCatalogAssignmentChecklistStore,
  createInMemoryAuditCatalogAssignmentChecklistStore,
  createPostgresAuditCatalogAssignmentChecklistStore,
  createSqliteAuditCatalogAssignmentChecklistStore,
  type FileAuditCatalogAssignmentChecklistStoreOptions,
  type InMemoryAuditCatalogAssignmentChecklistStoreOptions,
  type PostgresAuditCatalogAssignmentChecklistStoreOptions,
  resolveAuditCatalogAssignmentChecklistsFilePath,
  type SqliteAuditCatalogAssignmentChecklistStoreOptions,
} from "./catalog-assignment-checklist-store";
export {
  type ConfiguredAuditCatalogChecklistItemAcknowledgmentStoreOptions,
  createConfiguredAuditCatalogChecklistItemAcknowledgmentStore,
  createFileAuditCatalogChecklistItemAcknowledgmentStore,
  createInMemoryAuditCatalogChecklistItemAcknowledgmentStore,
  createPostgresAuditCatalogChecklistItemAcknowledgmentStore,
  createSqliteAuditCatalogChecklistItemAcknowledgmentStore,
  type FileAuditCatalogChecklistItemAcknowledgmentStoreOptions,
  type InMemoryAuditCatalogChecklistItemAcknowledgmentStoreOptions,
  type PostgresAuditCatalogChecklistItemAcknowledgmentStoreOptions,
  resolveAuditCatalogChecklistItemAcknowledgmentFilePath,
  type SqliteAuditCatalogChecklistItemAcknowledgmentStoreOptions,
} from "./catalog-checklist-item-acknowledgment-store";
export {
  type ConfiguredAuditCatalogChecklistItemAttestationStoreOptions,
  createConfiguredAuditCatalogChecklistItemAttestationStore,
  createFileAuditCatalogChecklistItemAttestationStore,
  createInMemoryAuditCatalogChecklistItemAttestationStore,
  createPostgresAuditCatalogChecklistItemAttestationStore,
  createSqliteAuditCatalogChecklistItemAttestationStore,
  type FileAuditCatalogChecklistItemAttestationStoreOptions,
  type InMemoryAuditCatalogChecklistItemAttestationStoreOptions,
  type PostgresAuditCatalogChecklistItemAttestationStoreOptions,
  resolveAuditCatalogChecklistItemAttestationFilePath,
  type SqliteAuditCatalogChecklistItemAttestationStoreOptions,
} from "./catalog-checklist-item-attestation-store";
export {
  type ConfiguredAuditCatalogChecklistItemBlockerStoreOptions,
  createConfiguredAuditCatalogChecklistItemBlockerStore,
  createFileAuditCatalogChecklistItemBlockerStore,
  createInMemoryAuditCatalogChecklistItemBlockerStore,
  createPostgresAuditCatalogChecklistItemBlockerStore,
  createSqliteAuditCatalogChecklistItemBlockerStore,
  type FileAuditCatalogChecklistItemBlockerStoreOptions,
  type InMemoryAuditCatalogChecklistItemBlockerStoreOptions,
  type PostgresAuditCatalogChecklistItemBlockerStoreOptions,
  resolveAuditCatalogChecklistItemBlockersFilePath,
  type SqliteAuditCatalogChecklistItemBlockerStoreOptions,
} from "./catalog-checklist-item-blocker-store";
export {
  type ConfiguredAuditCatalogChecklistItemEvidenceStoreOptions,
  createConfiguredAuditCatalogChecklistItemEvidenceStore,
  createFileAuditCatalogChecklistItemEvidenceStore,
  createInMemoryAuditCatalogChecklistItemEvidenceStore,
  createPostgresAuditCatalogChecklistItemEvidenceStore,
  createSqliteAuditCatalogChecklistItemEvidenceStore,
  type FileAuditCatalogChecklistItemEvidenceStoreOptions,
  type InMemoryAuditCatalogChecklistItemEvidenceStoreOptions,
  type PostgresAuditCatalogChecklistItemEvidenceStoreOptions,
  resolveAuditCatalogChecklistItemEvidenceFilePath,
  type SqliteAuditCatalogChecklistItemEvidenceStoreOptions,
} from "./catalog-checklist-item-evidence-store";
export {
  type ConfiguredAuditCatalogChecklistItemProgressStoreOptions,
  createConfiguredAuditCatalogChecklistItemProgressStore,
  createFileAuditCatalogChecklistItemProgressStore,
  createInMemoryAuditCatalogChecklistItemProgressStore,
  createPostgresAuditCatalogChecklistItemProgressStore,
  createSqliteAuditCatalogChecklistItemProgressStore,
  type FileAuditCatalogChecklistItemProgressStoreOptions,
  type InMemoryAuditCatalogChecklistItemProgressStoreOptions,
  type PostgresAuditCatalogChecklistItemProgressStoreOptions,
  resolveAuditCatalogChecklistItemProgressFilePath,
  type SqliteAuditCatalogChecklistItemProgressStoreOptions,
} from "./catalog-checklist-item-progress-store";
export {
  type ConfiguredAuditCatalogChecklistItemResolutionStoreOptions,
  createConfiguredAuditCatalogChecklistItemResolutionStore,
  createFileAuditCatalogChecklistItemResolutionStore,
  createInMemoryAuditCatalogChecklistItemResolutionStore,
  createPostgresAuditCatalogChecklistItemResolutionStore,
  createSqliteAuditCatalogChecklistItemResolutionStore,
  type FileAuditCatalogChecklistItemResolutionStoreOptions,
  type InMemoryAuditCatalogChecklistItemResolutionStoreOptions,
  type PostgresAuditCatalogChecklistItemResolutionStoreOptions,
  resolveAuditCatalogChecklistItemResolutionsFilePath,
  type SqliteAuditCatalogChecklistItemResolutionStoreOptions,
} from "./catalog-checklist-item-resolution-store";
export {
  type ConfiguredAuditCatalogChecklistItemSignoffStoreOptions,
  createConfiguredAuditCatalogChecklistItemSignoffStore,
  createFileAuditCatalogChecklistItemSignoffStore,
  createInMemoryAuditCatalogChecklistItemSignoffStore,
  createPostgresAuditCatalogChecklistItemSignoffStore,
  createSqliteAuditCatalogChecklistItemSignoffStore,
  type FileAuditCatalogChecklistItemSignoffStoreOptions,
  type InMemoryAuditCatalogChecklistItemSignoffStoreOptions,
  type PostgresAuditCatalogChecklistItemSignoffStoreOptions,
  resolveAuditCatalogChecklistItemSignoffFilePath,
  type SqliteAuditCatalogChecklistItemSignoffStoreOptions,
} from "./catalog-checklist-item-signoff-store";
export {
  type ConfiguredAuditCatalogChecklistItemVerificationStoreOptions,
  createConfiguredAuditCatalogChecklistItemVerificationStore,
  createFileAuditCatalogChecklistItemVerificationStore,
  createInMemoryAuditCatalogChecklistItemVerificationStore,
  createPostgresAuditCatalogChecklistItemVerificationStore,
  createSqliteAuditCatalogChecklistItemVerificationStore,
  type FileAuditCatalogChecklistItemVerificationStoreOptions,
  type InMemoryAuditCatalogChecklistItemVerificationStoreOptions,
  type PostgresAuditCatalogChecklistItemVerificationStoreOptions,
  resolveAuditCatalogChecklistItemVerificationsFilePath,
  type SqliteAuditCatalogChecklistItemVerificationStoreOptions,
} from "./catalog-checklist-item-verification-store";
export {
  type ConfiguredAuditCatalogReviewAssignmentStoreOptions,
  createConfiguredAuditCatalogReviewAssignmentStore,
  createFileAuditCatalogReviewAssignmentStore,
  createInMemoryAuditCatalogReviewAssignmentStore,
  createPostgresAuditCatalogReviewAssignmentStore,
  createSqliteAuditCatalogReviewAssignmentStore,
  type FileAuditCatalogReviewAssignmentStoreOptions,
  type InMemoryAuditCatalogReviewAssignmentStoreOptions,
  type PostgresAuditCatalogReviewAssignmentStoreOptions,
  resolveAuditCatalogReviewAssignmentsFilePath,
  type SqliteAuditCatalogReviewAssignmentStoreOptions,
} from "./catalog-review-assignment-store";
export {
  type ConfiguredAuditCatalogReviewSignalStoreOptions,
  createConfiguredAuditCatalogReviewSignalStore,
  createFileAuditCatalogReviewSignalStore,
  createInMemoryAuditCatalogReviewSignalStore,
  createPostgresAuditCatalogReviewSignalStore,
  createSqliteAuditCatalogReviewSignalStore,
  type FileAuditCatalogReviewSignalStoreOptions,
  type InMemoryAuditCatalogReviewSignalStoreOptions,
  type PostgresAuditCatalogReviewSignalStoreOptions,
  resolveAuditCatalogReviewSignalsFilePath,
  type SqliteAuditCatalogReviewSignalStoreOptions,
} from "./catalog-review-signal-store";
export {
  type ConfiguredAuditViewCatalogStoreOptions,
  createConfiguredAuditViewCatalogStore,
  createFileAuditViewCatalogStore,
  createInMemoryAuditViewCatalogStore,
  createPostgresAuditViewCatalogStore,
  createSqliteAuditViewCatalogStore,
  type FileAuditViewCatalogStoreOptions,
  type InMemoryAuditViewCatalogStoreOptions,
  type PostgresAuditViewCatalogStoreOptions,
  resolveAuditViewCatalogFilePath,
  type SqliteAuditViewCatalogStoreOptions,
} from "./catalog-store";
export {
  type ConfiguredAuditCatalogVisibilityStoreOptions,
  createConfiguredAuditCatalogVisibilityStore,
  createFileAuditCatalogVisibilityStore,
  createInMemoryAuditCatalogVisibilityStore,
  createPostgresAuditCatalogVisibilityStore,
  createSqliteAuditCatalogVisibilityStore,
  type FileAuditCatalogVisibilityStoreOptions,
  type InMemoryAuditCatalogVisibilityStoreOptions,
  type PostgresAuditCatalogVisibilityStoreOptions,
  resolveAuditCatalogVisibilityFilePath,
  type SqliteAuditCatalogVisibilityStoreOptions,
} from "./catalog-visibility-store";
export {
  type ConfiguredRuntimePersistenceOptions,
  createConfiguredRuntimePersistence,
  createPostgresRuntimePersistence,
  createSqliteRuntimePersistence,
  type MigrationResult,
  migratePostgresPersistence,
  migrateSqlitePersistence,
  type PostgresRuntimePersistenceOptions,
  type SqliteRuntimePersistenceOptions,
} from "./database-store";
export {
  type ConfiguredDispatchQueueOptions,
  createConfiguredDispatchQueue as createConfiguredRunDispatchQueue,
  createConfiguredDispatchQueue,
  createPostgresDispatchQueue,
  createSqliteDispatchQueue,
  type PostgresDispatchQueueOptions,
  type SqliteDispatchQueueOptions,
} from "./dispatch-store";
export type { PersistenceDialect } from "./migrations";
export {
  type ApprovalRepository,
  type CheckpointRepository,
  type CheckpointWrite,
  createFileRuntimePersistence,
  createInMemoryRuntimePersistence,
  createRuntimePersistenceSnapshot,
  type EventRepository,
  type FileRuntimePersistenceOptions,
  type InMemoryRuntimePersistenceOptions,
  type RunRepository,
  type RuntimePersistence,
  type RuntimePersistenceSnapshot,
  type RuntimeTransitionCommit,
  type RuntimeTransitionCommitResult,
} from "./runtime-store";
export {
  type ConfiguredSavedAuditViewStoreOptions,
  createConfiguredSavedAuditViewStore,
  createFileSavedAuditViewStore,
  createInMemorySavedAuditViewStore,
  createPostgresSavedAuditViewStore,
  createSqliteSavedAuditViewStore,
  type FileSavedAuditViewStoreOptions,
  type InMemorySavedAuditViewStoreOptions,
  type PostgresSavedAuditViewStoreOptions,
  resolveSavedAuditViewsFilePath,
  type SqliteSavedAuditViewStoreOptions,
} from "./saved-view-store";
export {
  type ConfiguredToolHistoryStoreOptions,
  createConfiguredToolHistoryStore,
  createFileToolHistoryStore,
  createInMemoryToolHistoryStore,
  createPostgresToolHistoryStore,
  createSqliteToolHistoryStore,
  type FileToolHistoryStoreOptions,
  type InMemoryToolHistoryStoreOptions,
  type PostgresToolHistoryStoreOptions,
  resolveToolHistoryFilePath,
  type SqliteToolHistoryStoreOptions,
} from "./tool-history-store";

export const persistencePackageBoundary = {
  name: "@runroot/persistence",
  kind: "package",
  phaseOwned: 2,
  responsibility:
    "Repository contracts, checkpoint storage, database adapters, dispatch queue persistence seams, tool-history storage adapters, additive saved-audit-view adapters, additive audit-view-catalog adapters, additive catalog-visibility adapters, additive catalog-review-signal adapters, additive catalog-review-assignment adapters, additive catalog-assignment-checklist adapters, additive checklist-item-progress adapters, additive checklist-item-blocker adapters, additive checklist-item-resolution adapters, additive checklist-item-verification adapters, additive checklist-item-evidence adapters, additive checklist-item-attestation adapters, and additive checklist-item-acknowledgment adapters.",
  publicSurface: [
    "repository interfaces",
    "storage adapters",
    "checkpoint persistence",
    "dispatch queue adapters",
    "tool history adapters",
    "saved audit view adapters",
    "audit view catalog adapters",
    "catalog visibility adapters",
    "catalog review signal adapters",
    "catalog review assignment adapters",
    "catalog assignment checklist adapters",
    "checklist item progress adapters",
    "checklist item blocker adapters",
    "checklist item resolution adapters",
    "checklist item verification adapters",
    "checklist item evidence adapters",
    "checklist item attestation adapters",
  ],
} as const satisfies PackageBoundary;
